### PR TITLE
Fix ipremote memory leaks

### PR DESCRIPTION
**Pull request by antonmes**
Closes https://github.com/VeniceX/CLibvenice/issues/3

### CODE REVIEW

**Comment by antonmes** [comment]
@czechboy0 please test

**Comment by czechboy0** [comment]
@antonmes Am I a CI bot now? 😆

**Comment by czechboy0** [comment]
BOOM 🎉 
screenshot 2016-05-10 19 25 41

**Comment by paulofaria** [comment]
@antonmes thats a fix from libmill?

**Comment by antonmes** [comment]
@paulofaria no, but it may be 😄 pushed a pr to libmill, should we wait for approval?

**Comment by paulofaria** [comment]
@antonmes haha I think they could've fixed in the latest versions. we haven't updates yet. maybe martin fixed it in a "better" way. After all he's the one who created the framework hahah.

**Comment by paulofaria** [comment]
LGTM! @antonmes

**Pull request merged**
