### PR TITLE
Fix package url

### PR DESCRIPTION
**Pull request by antonmes**

### CODE REVIEW

**Comment by Danappelxx** [comment]
LGTM - doesn't seem like something you'd need to make a pr for, though. I'll hold off on merging since there might be a reason why you didn't commit directly.

**Comment by antonmes** [comment]
i don't have push access here. 🐣

**Comment by Danappelxx** [comment]
Lemme see if I can fix that...

**Comment by paulofaria** [comment]
😱 I thought I fixed that! Also tomorrow I'll add everybody in Zewo org to VeniceX and AnnecyX

**Comment by paulofaria** [comment]
If no one does it before me. But I think I'm the only o e at AnnecyX currently

**Pull request merged**
